dist: bionic
language: csharp
solution: Etdb.MessagingService.AspNetCore.sln
mono: none
dotnet: 3.1.100
env:
  global:
    - DocumentDbContextOptions__ConnectionString="mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017"
    - DocumentDbContextOptions__DatabaseName="Etdb_MessagingService_Travis"
    - RedisCacheOptions__Configuration="${RedisConnection}"
    - RedisCacheOptions__InstanceName="Etdb_MessagingService_Travis"
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      services: 
        - mongodb
        - redis-server
      before_script:
        - sh setup-mongodb-user.sh "$MONGODB_USERNAME" "$MONGODB_PASSWORD"
      script: ./run-tests.sh

